"""Build the static store website and JSON feed from apps/.

Output (for the default base path /ps5/):

    dist/_headers, dist/_redirects, dist/404.html, dist/robots.txt
    dist/ps5/index.html                 store front
    dist/ps5/app/<TITLEID>/index.html   one page per app
    dist/ps5/catalog/v1.json            machine-readable feed
    dist/ps5/assets/…                   content-hashed CSS, JS and icons

Each theme under site/themes/<name>/ provides base.html, index.html, app.html,
404.html, card.html, optionally shelf.html, and style.css. Templates use
string.Template placeholders; every metadata value is HTML-escaped before it is
substituted.

Icons are fetched once per build and re-served from the site, resized to WebP
when Pillow is installed. A failed icon falls back to a placeholder instead of
failing the build.
"""

from __future__ import annotations

import hashlib
import html
import io
import json
import os
import shutil
import subprocess
from pathlib import Path
from string import Template
from urllib.parse import unquote

from . import artifacts
from .records import KINDS, Record, load_catalog
from .report import Report

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
REPO_URL = "https://github.com/blackbearreloaded/ps5-homebrew-catalog"
DEFAULT_SITE_URL = "https://homebrew.page"
DEFAULT_BASE = "/ps5/"
MARKER = ".catalog-site"
FEED_SCHEMA = 1
ICON_SIZE = 512
FONT_URL = "https://fonts.googleapis.com/css2?{families}&display=swap"
THEMES = {
    # name: (Google Fonts families, browser theme-color)
    "nebula": ("family=Sora:wght@300;400;500;600;700;800", "#05060f"),
    "cartridge": ("family=Press+Start+2P&family=VT323", "#1b1340"),
    "holo": ("family=Unbounded:wght@500;700;800&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,700", "#0b0b10"),
}
DEFAULT_THEME = "nebula"
FORMAT_LABELS = {"zip": "ZIP folder", "ffpkg": "FFPKG image", "ffpfsc": "FFPFSC image"}
KIND_LABELS = {"app": "App", "game": "Game", "tool": "Tool"}
KIND_PLURALS = {"app": "Apps", "game": "Games", "tool": "Tools"}


def e(value) -> str:
    return html.escape(str(value), quote=True)


def artifact_format(record: Record) -> str:
    return record.asset_name.rsplit(".", 1)[1].lower()


def source_commit() -> str:
    for key in ("CF_PAGES_COMMIT_SHA", "GITHUB_SHA"):
        if os.environ.get(key):
            return os.environ[key]
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, check=True,
                              capture_output=True, text=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def normalize_base(base: str) -> str:
    base = "/" + base.strip("/") + "/"
    return "/" if base == "//" else base


class Theme:
    def __init__(self, name: str):
        if name not in THEMES:
            raise ValueError(f"unknown theme {name!r}")
        self.name = name
        self.directory = SITE / "themes" / name
        self.fonts, self.color = THEMES[name]

    def template(self, name: str) -> Template | None:
        path = self.directory / name
        return Template(path.read_text(encoding="utf-8")) if path.is_file() else None

    def render(self, name: str, values: dict) -> str:
        template = self.template(name)
        return template.substitute(values) if template else ""


class Assets:
    """Writes content-hashed files under <base>/assets/ and remembers their URLs."""

    def __init__(self, directory: Path, url_prefix: str):
        self.directory = directory
        self.url_prefix = url_prefix
        directory.mkdir(parents=True, exist_ok=True)

    def add(self, stem: str, extension: str, content: bytes) -> str:
        name = f"{stem}.{hashlib.sha256(content).hexdigest()[:12]}.{extension}"
        (self.directory / name).write_bytes(content)
        return self.url_prefix + name


def process_icon(data: bytes) -> tuple[bytes, str]:
    image_format, _ = artifacts.inspect_icon(data)
    if image_format is None:
        raise ValueError("not a PNG, JPEG or WebP image")
    try:
        from PIL import Image
    except ImportError:
        return data, {"png": "png", "jpeg": "jpg", "webp": "webp"}[image_format]
    with Image.open(io.BytesIO(data)) as image:
        image = image.convert("RGBA")
        image.thumbnail((ICON_SIZE, ICON_SIZE))
        output = io.BytesIO()
        image.save(output, "WEBP", quality=82, method=6)
    return output.getvalue(), "webp"


def _prepare_output(out: Path) -> None:
    if out.exists():
        if not (out / MARKER).exists() and any(out.iterdir()):
            raise SystemExit(f"refusing to replace {out}: it is not empty and was not created by this build")
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text("Generated by python3 -m catalog build; safe to delete.\n", encoding="utf-8")


def _install_steps(record: Record) -> str:
    d = record.data
    name = f"<code>{e(unquote(record.asset_name))}</code>"
    loader = '<a href="https://github.com/drakmor/ShadowMountPlus">ShadowMountPlus</a>'
    if artifact_format(record) == "zip":
        steps = [
            f"Download {name} and extract it on your computer.",
            f"Copy the extracted <code>{e(d['titleid'])}/</code> folder to <code>/data/homebrew/</code> on your PS5, for example over FTP.",
            f"A loader such as {loader} picks it up. Launch {e(d['name'])} from the home screen.",
        ]
    else:
        steps = [
            f"Download {name}.",
            "Copy the file as-is to <code>/data/homebrew/</code> on your PS5, for example over FTP.",
            f"{loader} mounts the image. Launch {e(d['name'])} from the home screen.",
        ]
    return "\n".join(f"<li>{step}</li>" for step in steps)


def build_site(out: Path, apps_dir: Path, report: Report, base: str = DEFAULT_BASE,
               site_url: str = DEFAULT_SITE_URL, fetch_icons: bool = True,
               theme: str = DEFAULT_THEME) -> int:
    theme_obj = Theme(theme)
    records = load_catalog(apps_dir, report)
    if report.failed:
        return 0
    records.sort(key=lambda r: (r.data["name"].casefold(), r.titleid))
    base = normalize_base(base)
    site_url = site_url.rstrip("/")
    commit = source_commit()

    _prepare_output(out)
    root = out / base.strip("/") if base != "/" else out
    root.mkdir(parents=True, exist_ok=True)
    assets = Assets(root / "assets", base + "assets/")
    shared_dir = SITE / "shared"
    css = assets.add(f"{theme}", "css", (theme_obj.directory / "style.css").read_bytes())
    js = assets.add("app", "js", (shared_dir / "app.js").read_bytes())
    placeholder = assets.add("placeholder", "svg", (shared_dir / "placeholder.svg").read_bytes())
    shutil.copyfile(shared_dir / "favicon.svg", root / "favicon.svg")

    icons: dict[str, str] = {}
    for record in records:
        icons[record.titleid] = placeholder
        if not fetch_icons:
            continue
        try:
            content, extension = process_icon(artifacts.fetch_small(record.data["icon_url"], artifacts.MAX_ICON_BYTES))
        except (artifacts.DownloadError, OSError, ValueError) as error:
            report.warning(f"apps/{record.path.name}", f"icon not included, using a placeholder: {error}")
            continue
        icons[record.titleid] = assets.add(f"icon-{record.titleid}", extension, content)

    kinds = {kind: [r for r in records if r.data["kind"] == kind] for kind in KINDS}
    total = len(records)

    def page_url(record: Record) -> str:
        return f"{base}app/{record.titleid}/"

    def app_values(record: Record, number: int) -> dict:
        d = record.data
        fmt = artifact_format(record)
        values = {k: e(v) for k, v in d.items()}
        values.update(
            url=e(page_url(record)),
            icon=e(icons[record.titleid]),
            kind_label=e(KIND_LABELS[d["kind"]]),
            format=e(fmt),
            format_label=e(FORMAT_LABELS[fmt]),
            artifact_name=e(unquote(record.asset_name)),
            source_short=e(f"{record.owner}/{record.repo}"),
            release_url=e(f"{d['source_repo']}/releases/tag/{d['artifact_url'].split('/releases/download/')[1].split('/')[0]}"),
            tag=e(record.tag),
            number=f"{number:03d}",
            total=f"{total:03d}",
            search_text=e(" ".join((d["name"], d["author"], d["titleid"], d["description"], d["kind"]))),
        )
        return values

    numbered = {r.titleid: app_values(r, i) for i, r in enumerate(sorted(records, key=lambda r: r.titleid), 1)}

    def cards(selection: list[Record], in_grid: bool) -> str:
        rendered = []
        for record in selection:
            values = dict(numbered[record.titleid])
            values["grid_attrs"] = (f' data-app data-app-kind="{values["kind"]}" data-search-text="{values["search_text"]}"'
                                    if in_grid else "")
            rendered.append(theme_obj.render("card.html", values))
        return "\n".join(rendered)

    shared = {
        "base": base,
        "repo": REPO_URL,
        "submit_url": f"{REPO_URL}/blob/main/docs/submitting.md",
        "css": css,
        "js": js,
        "fonts": e(FONT_URL.format(families=theme_obj.fonts)),
        "theme_color": theme_obj.color,
        "commit": e(commit),
        "commit_short": e(commit[:7]),
        "app_count": total,
        "developer_count": len({r.owner.casefold() for r in records}),
        "game_count": len(kinds["game"]),
        "apps_only_count": len(kinds["app"]),
        "tool_count": len(kinds["tool"]),
        "feed_url": f"{base}catalog/v1.json",
    }
    for key in ("app_count", "developer_count", "game_count", "apps_only_count", "tool_count"):
        shared[f"{key}_pad"] = f"{shared[key]:03d}"
    base_tpl = theme_obj.template("base.html")

    def write_page(path: Path, *, title: str, description: str, canonical: str, body: str,
                   og_image: str | None = None, page_class: str = "") -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(base_tpl.substitute(
            shared, title=e(title), description=e(description), canonical=e(canonical),
            og_image=e(og_image or site_url + base + "favicon.svg"), body=body, page_class=page_class,
        ), encoding="utf-8")

    # Store front.
    spotlight = records[int(hashlib.sha256(commit.encode()).hexdigest(), 16) % total] if total else None
    chips = [f'<button type="button" class="chip" data-kind="all" aria-pressed="true">All <span>{total}</span></button>']
    chips += [f'<button type="button" class="chip" data-kind="{kind}" aria-pressed="false">{KIND_PLURALS[kind]} <span>{len(items)}</span></button>'
              for kind, items in kinds.items() if items]
    shelves = "\n".join(
        theme_obj.render("shelf.html", dict(shared, kind=kind, kind_plural=KIND_PLURALS[kind],
                                            count=len(items), cards=cards(items, in_grid=False)))
        for kind, items in kinds.items() if items
    )
    spot = {f"spot_{k}": v for k, v in (numbered[spotlight.titleid] if spotlight else {}).items()}
    fan = [icons[r.titleid] for r in records[:3]] + [placeholder] * 3
    index_body = theme_obj.template("index.html").safe_substitute(
        dict(shared, **spot), chips="".join(chips), shelves=shelves, cards=cards(records, in_grid=True),
        fan_icon_1=e(fan[0]), fan_icon_2=e(fan[1]), fan_icon_3=e(fan[2]),
    )
    write_page(root / "index.html", title="PS5 Homebrew Store — community apps, games and tools",
               description=f"Browse {total} PS5 homebrew apps, games and tools. Every download comes from "
                           "the developer's GitHub release and is pinned by SHA-256.",
               canonical=site_url + base, body=index_body, page_class="page-home")

    # App pages.
    for record in records:
        values = dict(shared, **numbered[record.titleid], steps=_install_steps(record))
        write_page(root / "app" / record.titleid / "index.html",
                   title=f"{record.data['name']} — PS5 Homebrew Store", description=record.data["description"],
                   canonical=site_url + page_url(record), body=theme_obj.render("app.html", values),
                   og_image=site_url + icons[record.titleid], page_class="page-app")

    # 404 page, served by Cloudflare Pages for unknown paths.
    for target in {out / "404.html", root / "404.html"}:
        write_page(target, title="Not found — PS5 Homebrew Store", description="Page not found.",
                   canonical=site_url + base, body=theme_obj.render("404.html", shared), page_class="page-404")

    # Feed for the console store and other clients.
    feed = {
        "schema": FEED_SCHEMA,
        "name": "PS5 Homebrew Catalog",
        "homepage": site_url + base,
        "source": {"repository": REPO_URL, "commit": commit},
        "apps": [
            {**r.data, "format": artifact_format(r), "page": site_url + page_url(r), "icon": site_url + icons[r.titleid]}
            for r in sorted(records, key=lambda r: r.titleid)
        ],
    }
    (root / "catalog").mkdir()
    (root / "catalog" / "v1.json").write_text(json.dumps(feed, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Cloudflare Pages configuration.
    csp = ("default-src 'self'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; "
           "font-src https://fonts.gstatic.com; script-src 'self'; connect-src 'self'; "
           "base-uri 'self'; form-action 'none'; frame-ancestors 'none'")
    (out / "_headers").write_text(f"""/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Content-Security-Policy: {csp}

{base}assets/*
  Cache-Control: public, max-age=31536000, immutable

{base}catalog/*
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=300, must-revalidate
""", encoding="utf-8")
    if base != "/":
        (out / "_redirects").write_text(f"/ {base} 302\n{base.rstrip('/')} {base} 301\n", encoding="utf-8")
    (out / "robots.txt").write_text("User-agent: *\nAllow: /\n", encoding="utf-8")
    return total
